# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            JamesLaddCode
tagline:          'Ramblings and opinions on code - mostly.'
description:      'A collection of of posts relating to software writing, quality & practices with occasional rants.'
url:              http://jamesladdcode.com
baseurl:          /

author:
  name:           'James Ladd'
  url:            https://twitter.com/jamesladd

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jamesladd/jamesladdcode

gems:
  - jekyll-feed
  - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock

